### PR TITLE
update rainglow docs

### PR DESCRIPTION
**Pull request by orifu**
yay

---
[preview this pull request!](https://pull-1.rosebud.pages.dev)

### CODE REVIEW

**Review by ix0rai — APPROVED** [review]
great rewrite why are we hating on tslat's colour picker though

it's my favourite

**Comment by orifu** [comment]
> great rewrite why are we hating on tslat's colour picker though
> 
> it's my favourite

bc its http and ugly #itstimetomoveon

**Comment by ix0rai** [comment]
what about java packed int :sob:

**Comment by orifu** [comment]
when would you need that????? its just the hex code in decimal anyway

**Pull request merged**
